namespace AndroidX.Compose.SourceGenerators;

/// <summary>
/// Source text added to the user's compilation via
/// <see cref="Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput"/>.
/// </summary>
internal static class Attributes
{
    public const string Source = """
        // <auto-generated/>
        #nullable enable
        namespace AndroidX.Compose
        {
            /// <summary>
            /// Apply at assembly scope to generate a named-bit
            /// <c>[Flags] internal enum &lt;EnumName&gt;</c> from the
            /// parameter shape of <typeparamref name="T"/>'s static
            /// method named by the constructor's <c>methodName</c>
            /// argument. Bit numbers match the Kotlin parameter index
            /// in the bytecode — the position the <c>$default</c>
            /// bitmask expects.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly,
                                           AllowMultiple = true)]
            internal sealed class ComposeDefaultsAttribute<T> : global::System.Attribute
            {
                public ComposeDefaultsAttribute(string methodName, string enumName) { }
            }

            /// <summary>
            /// Apply at assembly scope to generate a named-bit
            /// <c>[Flags] internal enum &lt;EnumName&gt;</c> from an
            /// explicit positional parameter list. Use this overload
            /// when the Kotlin <c>$default</c>-bearing overload was
            /// stripped from the binding (mangled JVM name, inline-class
            /// param, etc.) and there is no <c>IMethodSymbol</c> to read.
            /// Each name occupies one bit at its index; prefix a name
            /// with <c>!</c> to consume the bit without emitting an
            /// enum member (e.g. params the caller always provides).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly,
                                           AllowMultiple = true)]
            internal sealed class ComposeDefaultsAttribute : global::System.Attribute
            {
                public ComposeDefaultsAttribute(string enumName, params string[] parameterNames) { }
            }

            /// <summary>
            /// Apply to a <c>partial</c> static method on
            /// <c>ComposeBridges</c> to have AndroidX.Compose.SourceGenerators
            /// emit its JNI-bridge body. The partial method declares the
            /// user-facing C# signature; the generator fills in cache
            /// fields, lazy class/method ID resolution, the JValue array,
            /// the <c>$default</c> bitmask, and the
            /// <c>try</c>/<c>finally</c> + <c>GC.KeepAlive</c> block.
            /// </summary>
            /// <remarks>
            /// <para><b>Class</b>: JNI-internal class name, e.g.
            /// <c>androidx/compose/material3/ButtonKt</c>.</para>
            /// <para><b>JvmName</b>: the (often mangled) Kotlin-emitted
            /// method name, e.g. <c>Button</c> or <c>Surface-T9BRK9s</c>.</para>
            /// <para><b>Signature</b>: full JNI signature string for the
            /// underlying static method. Ends in
            /// <c>...Composer;I*I)&lt;ReturnType&gt;</c> (one trailing
            /// <c>I</c> per <c>$changed</c> group plus one for
            /// <c>$default</c>) when the function has at least one
            /// defaultable parameter, or <c>...Composer;I*)&lt;ReturnType&gt;</c>
            /// when every parameter is required (no <c>$default</c> slot
            /// in the bytecode). The return-type token is <c>V</c> for
            /// <c>void</c> bridges or an <c>L...;</c> for state holders /
            /// factories.</para>
            /// <para><b>Defaults</b>: <c>typeof(XxxDefault)</c> — the
            /// <c>$default</c> bitmask enum produced by
            /// <see cref="ComposeDefaultsAttribute"/>. The generator reads
            /// the matching declarative <c>[ComposeDefaults(...)]</c>
            /// attribute to learn the Kotlin parameter names + bit
            /// positions. Required when the JNI signature has a
            /// <c>$default</c> slot; must be omitted otherwise. The
            /// generator cross-checks this against the signature and
            /// reports CN2005 on a mismatch.</para>
            /// <para><b>InstanceField</b>: when set, the bridge calls an
            /// instance method on a Kotlin <c>object</c> singleton — name
            /// the <c>$$INSTANCE</c>-style static field
            /// (e.g. <c>INSTANCE</c>) and the generator emits
            /// <c>GetMethodID</c> + <c>CallObjectMethod</c> instead.</para>
            /// <para><b>Suspend</b>: opts into the Kotlin <c>suspend</c>
            /// bridge shape. The trailing C# parameter must be
            /// <c>Kotlin.Coroutines.IContinuation</c> (or an implementor —
            /// <c>SuspendContinuation</c> works), the C# return type must
            /// be <c>System.IntPtr</c> (raw — boxing into a
            /// <see cref="global::Java.Lang.Object"/> peer would collide
            /// with Mono's peer cache for the <c>COROUTINE_SUSPENDED</c>
            /// singleton), and the JNI return type must be
            /// <c>Ljava/lang/Object;</c>. The generator detects two
            /// sub-shapes from the JNI signature:
            /// <list type="bullet">
            /// <item><description><b>Instance suspend</b> (no trailing
            /// <c>I L&lt;Object&gt;</c>): the first C# user parameter
            /// (which must be <c>IntPtr</c>) is the receiver; the bridge
            /// emits <c>GetMethodID</c> + <c>CallObjectMethod(receiver,
            /// ...)</c> and the receiver is NOT in the JNI signature.</description></item>
            /// <item><description><b>Static <c>$default</c> suspend</b>
            /// (trailing <c>I L&lt;Object&gt;</c>): same shape as
            /// <see cref="ComposeBridgeAttribute"/>'s extension-with-default
            /// flow — the first C# user parameter is the receiver AND
            /// occupies JNI slot 0; the bridge emits
            /// <c>GetStaticMethodID</c> + <c>CallStaticObjectMethod</c>.</description></item>
            /// </list>
            /// Cannot be combined with a Composer slot or a constructor
            /// <c>JvmName</c>.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method,
                                           AllowMultiple = false)]
            internal sealed class ComposeBridgeAttribute : global::System.Attribute
            {
                public ComposeBridgeAttribute() { }
                public string Class { get; set; } = "";
                public string JvmName { get; set; } = "";
                public string Signature { get; set; } = "";
                public global::System.Type? Defaults { get; set; }
                public string? InstanceField { get; set; }
                public bool Suspend { get; set; }
            }

            /// <summary>
            /// Apply alongside <see cref="ComposeBridgeAttribute"/> on a
            /// <c>partial</c> method in <c>ComposeBridges</c> to have
            /// <c>ComposeFacadeGenerator</c> emit the corresponding
            /// user-facing facade class (a <c>public sealed partial</c>
            /// <see cref="ComposableNode"/> / <see cref="ComposableContainer"/>
            /// in <c>namespace AndroidX.Compose</c>).
            /// </summary>
            /// <remarks>
            /// The facade's constructor, base class, and <c>Render</c> body
            /// are inferred from the bridge's C# parameter shape:
            /// <list type="bullet">
            /// <item><description><c>IModifier? modifier</c> → render uses
            /// <c>BuildModifier()</c>; no ctor param.</description></item>
            /// <item><description><c>IFunction0 &lt;name&gt;</c> → ctor takes
            /// <c>System.Action &lt;name&gt;</c>; render wraps in
            /// <c>ComposableLambda0</c>.</description></item>
            /// <item><description><c>IFunction2 content</c> /
            /// <c>IFunction3 content</c> → container shape, base
            /// <c>ComposableContainer</c>; render uses
            /// <c>ComposableLambdas.Wrap2</c> / <c>Wrap3</c>.</description></item>
            /// <item><description>Primitive (<c>string</c>, <c>int</c>,
            /// <c>long</c>, <c>bool</c>, <c>float</c>, <c>double</c>) →
            /// positional ctor parameter.</description></item>
            /// </list>
            /// Anything else (e.g. <c>IFunction1</c> callbacks, value-class
            /// handles, the caller-controlled <c>int defaults</c> hatch) is
            /// rejected via diagnostic CN3002 — leave that bridge hand-written.
            /// <para><b>Docs &amp; overrides:</b> the generated class is
            /// <c>sealed partial</c>. Add a sibling stub
            /// <c>src/Microsoft.AndroidX.Compose/&lt;Name&gt;.cs</c> with the
            /// <c>///&lt;summary&gt;</c> comment (and any extra members
            /// the facade needs) — the generator deliberately does not
            /// emit a summary so the stub owns it.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method,
                                           AllowMultiple = false)]
            internal sealed class ComposeFacadeAttribute : global::System.Attribute
            {
                public ComposeFacadeAttribute() { }

                /// <summary>Optional override for the generated class name. Defaults to the bridge method name.</summary>
                public string? ClassName { get; set; }

                /// <summary>
                /// Optional scope to publish from an <c>IFunction3</c> content
                /// lambda. <c>"Row"</c> (e.g. <see cref="NavigationBar"/>,
                /// <see cref="Badge"/>) or <c>"Column"</c>. The lambda
                /// receives the scope handle and pushes it via
                /// <c>RenderContext.PushScope(scope, ScopeKind.X)</c> so
                /// child composables can read it. Requires a bridge with
                /// an <c>IFunction3 content</c> parameter.
                /// </summary>
                public string? Scope { get; set; }

                /// <summary>
                /// Phase 6 — name of a <c>ColorScheme</c> property (e.g.
                /// <c>"secondaryContainer"</c>) to use as a runtime fallback
                /// when the user leaves the bridge's container-color
                /// parameter at its sentinel <c>0L</c>. The generator
                /// emits a <c>long ContainerColor { get; set; }</c>
                /// property and binds the named bridge param (see
                /// <see cref="ColorParameter"/>) to
                /// <c>ContainerColor != 0L ? ContainerColor :
                /// MaterialTheme.Instance.GetColorScheme(composer,0).&lt;Slot&gt;</c>.
                /// </summary>
                public string? DefaultColorFromTheme { get; set; }

                /// <summary>
                /// Phase 6 — the name of the bridge's <c>long</c>
                /// parameter that <see cref="DefaultColorFromTheme"/>
                /// targets. Optional when the bridge has exactly one
                /// <c>long</c> user parameter; required when there's
                /// ambiguity.
                /// </summary>
                public string? ColorParameter { get; set; }

                /// <summary>
                /// Phase 8 — fallback for the <c>$default</c> enum when
                /// the facade method has no paired
                /// <see cref="ComposeBridgeAttribute"/>. Used by tiny
                /// pass-through "wrapper" bridges (extended partial methods
                /// with hand-written bodies that delegate straight to a
                /// bound binding instead of doing JNI). Set this to
                /// <c>typeof(XxxDefault)</c> to drive the auto-mask logic
                /// for direct-binding facades. Bridge-mode facades read
                /// <c>Defaults</c> from their <c>[ComposeBridge]</c>
                /// instead — this property is ignored in that case.
                /// </summary>
                public global::System.Type? Defaults { get; set; }

                /// <summary>
                /// Opt in to hybrid container shape: bridge has exactly
                /// one non-nullable <c>IFunction2</c> or <c>IFunction3</c>
                /// body slot plus one or more nullable <c>IFunction2?</c> /
                /// <c>IFunction3?</c> slots. The non-nullable body slot
                /// becomes <c>RenderChildren</c> and the facade derives
                /// from <see cref="ComposableContainer"/>; the nullable
                /// slots surface as named <see cref="ComposableNode"/>?
                /// properties (Phase 3 style). For an <c>IFunction3</c>
                /// body, set <see cref="Scope"/> too if children need
                /// the published <c>RowScope</c>/<c>ColumnScope</c>. For
                /// an <c>IFunction2</c> body, <see cref="Scope"/> has no
                /// effect.
                /// </summary>
                public bool Container { get; set; }

                /// <summary>
                /// Phase 9 — name of a synthetic facade property that
                /// drives bridge branching. When the property is non-null
                /// at render time the generated <c>Render</c> routes to
                /// the <see cref="AlternateBridge"/> method on
                /// <c>ComposeBridges</c>; otherwise it calls the primary
                /// bridge (the one paired with this attribute's
                /// <see cref="ComposeBridgeAttribute"/>).
                /// </summary>
                /// <remarks>
                /// The property is synthesized from the extra
                /// <c>IFunction2</c>/<c>IFunction3</c> parameter that the
                /// alternate bridge has and the primary lacks. The value
                /// of <c>BranchOn</c> must equal the PascalCased Kotlin
                /// parameter name of that extra slot. The alternate's
                /// user parameters must form the primary's user-param
                /// name set plus exactly one extra slot. Must be paired
                /// with <see cref="AlternateBridge"/>.
                /// </remarks>
                public string? BranchOn { get; set; }

                /// <summary>
                /// Phase 9 — name of the sibling static partial method on
                /// <c>ComposeBridges</c> to route to when the facade's
                /// <see cref="BranchOn"/> property is non-null. The
                /// alternate must declare its own <see cref="ComposeBridgeAttribute"/>
                /// with a matching <c>Defaults</c> enum and accept all
                /// of the primary bridge's user parameters (by name) plus
                /// exactly one extra slot matching <see cref="BranchOn"/>.
                /// </summary>
                public string? AlternateBridge { get; set; }

                /// <summary>
                /// Opt in to publishing a per-child row position for the
                /// generated container body. The emitted <c>Wrap2</c> /
                /// <c>Wrap3</c> content lambda calls
                /// <c>RenderChildrenIndexed(c)</c> instead of
                /// <c>RenderChildren(c)</c>, which wraps every child
                /// in <c>RenderContext.PushRow(Children.Count)</c> +
                /// <c>SetIndex(i)</c> so a child composable
                /// (e.g. <see cref="SegmentedButton"/>) can read its
                /// position from <see cref="RenderContext.CurrentRowChildIndex"/>
                /// / <see cref="RenderContext.CurrentRowChildCount"/> to
                /// compute Kotlin defaults that depend on position
                /// (start/end shape, divider placement, ...). Only valid
                /// on a container facade — fails CN3006 if the bridge
                /// has no <c>IFunction2</c>/<c>IFunction3</c> body slot.
                /// </summary>
                public bool IndexedChildren { get; set; }

                /// <summary>
                /// Phase 11 — name of a sibling static method on
                /// <c>ComposeBridges</c> that the facade exposes as an
                /// extra ctor dispatching to a second bridge. The
                /// secondary's user parameters must equal the primary's
                /// shared (by-name) set plus exactly one extra
                /// non-nullable reference-type parameter (the
                /// "discriminator"). The generator adds a
                /// <c>readonly TDiscrim? _&lt;discriminator&gt;</c>
                /// backing field, an extra ctor whose first positional
                /// argument is the discriminator, and prepends a
                /// <c>if (_&lt;discriminator&gt; is not null) { call
                /// secondary; return; }</c> branch to <c>Render</c>.
                /// The primary's body keeps its existing shape (e.g.
                /// Phase 7 painter-id + painter ctors). Used by
                /// <see cref="Icon"/> to dispatch between the
                /// <c>ImageVector</c> overload (directly bound binding)
                /// and the <c>Painter</c> overload (JNI bridge).
                /// </summary>
                public string? SecondaryCtor { get; set; }

                /// <summary>
                /// Phase 11 — optional <c>$default</c> enum for the
                /// <see cref="SecondaryCtor"/> bridge. Reads
                /// <c>[ComposeBridge].Defaults</c> on the secondary
                /// method first; this property is the fallback when the
                /// secondary is a Phase 8-style wrapper without
                /// <c>[ComposeBridge]</c>.
                /// </summary>
                public global::System.Type? SecondaryDefaults { get; set; }
            }

            /// <summary>
            /// Phase 3 — apply to a Kotlin-function bridge parameter to
            /// override the C# property name the facade exposes for that
            /// slot. Default is the parameter name PascalCased. Useful
            /// when the Kotlin name reads awkwardly in C# (e.g.
            /// <c>content</c> → <c>Body</c>,
            /// <c>headlineContent</c> → <c>Headline</c>,
            /// <c>tooltip</c> → <c>Tip</c>).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter,
                                           AllowMultiple = false)]
            internal sealed class SlotAttribute : global::System.Attribute
            {
                public SlotAttribute(string propertyName) { }
            }

            /// <summary>
            /// Phase 2 — apply to an <c>IFunction1</c> bridge parameter
            /// to mark it as a typed C# callback. The facade gets an
            /// <c>Action&lt;T&gt;</c> ctor parameter; the generated
            /// <c>Render</c> body wraps it in a <c>ComposableLambda1</c>
            /// that un-boxes the Kotlin value for <c>T</c>.
            /// Supported <c>T</c>: <c>bool</c>, <c>string</c>, <c>float</c>.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter,
                                           AllowMultiple = false)]
            internal sealed class CallbackAttribute : global::System.Attribute
            {
                public CallbackAttribute(global::System.Type valueType) { }
            }

            /// <summary>
            /// Phase 7 — apply to the <c>Painter</c> bridge parameter
            /// that takes the resolved Painter wrapper. The facade
            /// replaces this parameter with a synthetic ctor argument
            /// <c>int drawableResourceId</c>; <c>Render</c> calls
            /// <c>ComposeBridges.PainterResource(id, composer)</c> to
            /// resolve the handle, wraps it into a managed
            /// <c>Painter</c> peer via
            /// <c>JniHandleOwnership.TransferLocalRef</c>, and forwards
            /// it to the annotated parameter. The bridge's
            /// auto-emitted <c>GC.KeepAlive(painter)</c> keeps the
            /// peer alive across the call. At most one bridge
            /// parameter may carry <c>[PainterResource]</c>.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter,
                                           AllowMultiple = false)]
            internal sealed class PainterResourceAttribute : global::System.Attribute
            {
                public PainterResourceAttribute() { }
            }

            /// <summary>
            /// Phase 4 — apply to the <c>IntPtr</c> bridge parameter that
            /// carries a Kotlin state-holder handle (e.g.
            /// <c>DatePickerState</c>, <c>DateRangePickerState</c>). The
            /// facade calls the named <c>Remember*State</c> bridge on
            /// <c>ComposeBridges</c> to resolve the handle, optionally
            /// binds it to a caller-supplied wrapper of type
            /// <see cref="StateType"/>, and forwards the handle to this
            /// parameter. The wrapper is exposed as a defaulted ctor
            /// argument (<c>StateType? state = null</c>).
            /// </summary>
            /// <remarks>
            /// <para><b>Remember</b>: the <c>nameof(ComposeBridges.X)</c>
            /// of a static partial bridge on <c>ComposeBridges</c> whose
            /// last parameter is an <c>IComposer</c> and that returns
            /// <c>IntPtr</c>. The remaining (leading) parameters are
            /// treated as init values — each one is read off the
            /// caller-supplied <c>StateType</c> wrapper at render time.
            /// Phase 4 covers the zero-user-param shape (e.g.
            /// <c>RememberDatePickerState(IComposer) -&gt; IntPtr</c>);
            /// Phase 4b adds support for parameterised remembers (e.g.
            /// <c>RememberTimePickerState(int, int, bool, IComposer)</c>).
            /// Each Remember user param must resolve to a readable
            /// instance member on <see cref="StateType"/>: the generator
            /// looks up the PascalCased name first (e.g.
            /// <c>initialHour</c> → <c>InitialHour</c>) and falls back
            /// to <c>Initial&lt;PascalCase&gt;</c> for the Kotlin
            /// convention where <c>initialX</c> remember args correspond
            /// to live wrapper property <c>X</c>.</para>
            /// <para><b>StateType</b>: the C# wrapper class that exposes
            /// the state-holder's properties. It must declare an
            /// instance, writable, non-readonly field named <c>Jvm</c>
            /// whose declared type is the binding-generated interface
            /// (e.g. <c>IDatePickerState</c>) — the generator emits
            /// <c>state.Jvm = Java.Lang.Object.GetObject&lt;IXxxState&gt;
            /// (handle, JniHandleOwnership.DoNotTransfer)!</c> the first
            /// time <c>Render</c> sees a non-null wrapper. For Phase 4b
            /// (parameterised Remember) the type must also be
            /// constructible with no arguments (parameterless ctor or
            /// all-defaulted-params ctor) so the facade can auto-create
            /// a default wrapper when the caller passes <c>null</c>.</para>
            /// <para><b>SharedState</b> (Phase 4c): when <c>true</c>,
            /// the generated <c>Render</c> preamble checks whether
            /// <c>_state.Jvm</c> is already populated (from an earlier
            /// sibling render that received the same wrapper instance)
            /// and skips the <c>RememberXxxState</c> call in that case,
            /// reusing the cached JNI handle directly. This lets two or
            /// more sibling facades share the same state-holder peer
            /// (e.g. a <see cref="TimePicker"/> and a
            /// <see cref="TimeInput"/> driven by the same
            /// <see cref="TimePickerState"/>). Defaults to <c>false</c>
            /// — every render calls Remember and Compose's slot-table
            /// caches per-call-site. Opt in only when the facade is
            /// designed to be paired with at least one sibling that
            /// uses the same <see cref="StateType"/>.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter,
                                           AllowMultiple = false)]
            internal sealed class StateHolderAttribute : global::System.Attribute
            {
                public StateHolderAttribute() { }
                public string Remember { get; set; } = "";
                public global::System.Type StateType { get; set; } = null!;
                public bool SharedState { get; set; }
            }

            /// <summary>
            /// Annotates an <c>IFunction1</c> parameter on a
            /// <c>Remember*State(…)</c> helper on <c>ComposeBridges</c>
            /// to tell <c>ComposeFacadeGenerator</c> that the value is
            /// a per-instance JNI veto adapter — Kotlin's
            /// <c>confirmStateChange</c> / <c>confirmValueChange</c>
            /// callback. The facade allocates the JCW once per node
            /// (<c>readonly</c> field) and exposes a
            /// <c>System.Func&lt;T, bool&gt;?</c> property the user
            /// can mutate freely without invalidating Kotlin's
            /// <c>remember</c> cache key (which is part of the
            /// Java identity of the adapter, not the C# delegate).
            /// </summary>
            /// <remarks>
            /// <para>The value type <c>T</c> is what the Kotlin
            /// callback receives (e.g. <c>DrawerValue</c>,
            /// <c>SheetValue</c>) and what the developer-facing
            /// <c>Func&lt;T, bool&gt;</c> takes.</para>
            /// <para><b>AdapterType</b> — JCW class implementing
            /// <c>Kotlin.Jvm.Functions.IFunction1</c> with a writable
            /// <c>System.Func&lt;T, bool&gt;? Callback</c> property the
            /// generator assigns from the facade's
            /// <see cref="PropertyName"/>. Must be registered with
            /// Mono.Android (<c>[Register]</c>) so its Java peer
            /// identity is stable. Defaults to convention
            /// <c>AndroidX.Compose.&lt;TName&gt;ConfirmStateChange</c>.</para>
            /// <para><b>PropertyName</b> — name of the property the
            /// facade exposes. Defaults to <c>ConfirmStateChange</c>.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter,
                                           AllowMultiple = false)]
            internal sealed class ConfirmStateChangeAttribute : global::System.Attribute
            {
                public ConfirmStateChangeAttribute(global::System.Type valueType) { }
                public global::System.Type? AdapterType { get; set; }
                public string? PropertyName { get; set; }
            }

            /// <summary>
            /// Apply to a <c>partial class</c> deriving from
            /// <see cref="global::Java.Lang.Object"/> to have
            /// AndroidX.Compose.SourceGenerators emit a cached
            /// accessor for the Kotlin <c>Companion</c> singleton and one
            /// implementing partial property per
            /// <see cref="ComposeCompanionGetterAttribute"/>. Eliminates the
            /// repeated raw-JNI plumbing that every Compose value-class /
            /// reference-class wrapper would otherwise hand-roll.
            /// </summary>
            /// <remarks>
            /// <para><b>outerJniClass</b>: the slash-separated JNI class
            /// name of the outer Kotlin type — e.g.
            /// <c>androidx/compose/ui/text/font/FontWeight</c>. The
            /// generator derives the companion JNI name by appending
            /// <c>$Companion</c>.</para>
            /// <para><b>InlineClass</b>: set <c>true</c> when the outer
            /// type is a Kotlin <c>@JvmInline value class</c> whose
            /// companion getters return the packed <c>int</c> value
            /// (Kotlin emits <c>getXxx-mangled()I</c>). The generator
            /// emits a helper that boxes the result via the synthesized
            /// static <c>box-impl(I)L&lt;outer&gt;;</c> method to produce
            /// the boxed reference expected by C# call sites.</para>
            /// <para>The defining partial declarations live in the user's
            /// hand-written file (so XML docs stay on the public surface);
            /// the generator emits the implementing partials, the
            /// per-property cache fields, the cached <c>Companion()</c>
            /// accessor, and one shared <c>ResolveSimple</c> or
            /// <c>ResolveInline</c> helper.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class,
                                           AllowMultiple = false)]
            internal sealed class ComposeCompanionAttribute : global::System.Attribute
            {
                public ComposeCompanionAttribute(string outerJniClass) { }
                public bool InlineClass { get; set; }
            }

            /// <summary>
            /// Apply to a <c>public static partial T PropertyName { get; }</c>
            /// declaration on a class carrying
            /// <see cref="ComposeCompanionAttribute"/>. The generator emits
            /// the implementing partial body that calls the named Kotlin
            /// getter on the cached Companion and wraps the resulting JNI
            /// handle in a fresh <c>T</c> peer via
            /// <c>(IntPtr, JniHandleOwnership.TransferLocalRef)</c>.
            /// </summary>
            /// <remarks>
            /// <para><b>getterName</b>: the exact Kotlin-emitted method
            /// name on the Companion class (e.g. <c>getThin</c>,
            /// <c>getCenter-e0LSkKk</c> for inline-class mangled names).
            /// Hyphens and other non-identifier characters are accepted —
            /// the generator forwards the string straight to
            /// <c>JNIEnv.GetMethodID</c>.</para>
            /// <para><b>ReturnDescriptor</b>: optional JNI return-type
            /// descriptor (e.g.
            /// <c>Landroidx/compose/ui/text/font/SystemFontFamily;</c>)
            /// for getters whose return type is a subtype of the outer
            /// class. Defaults to <c>L&lt;outerJniClass&gt;;</c>. Must
            /// not be set when the containing
            /// <see cref="ComposeCompanionAttribute"/> has
            /// <c>InlineClass = true</c> — inline-class getters always
            /// return packed <c>I</c> and the generator routes the
            /// boxed reference through the synthesized
            /// <c>box-impl(I)L&lt;outer&gt;;</c>.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Property,
                                           AllowMultiple = false)]
            internal sealed class ComposeCompanionGetterAttribute : global::System.Attribute
            {
                public ComposeCompanionGetterAttribute(string getterName) { }
                public string? ReturnDescriptor { get; set; }
            }
        }
        """;
}
