using System.Collections.Generic;
using System.Text;

namespace AndroidX.Compose.SourceGenerators;

/// <summary>
/// Emits the implementing partial of a <c>[ComposeCompanion]</c>-decorated
/// class: cache fields for the outer class / companion / per-property
/// peers, a lazy <c>Companion()</c> accessor that mirrors the
/// hand-written pattern (FindClass outer → GetStaticFieldID Companion →
/// NewGlobalRef the instance → DeleteLocalRef), one shared
/// <c>ResolveSimple(getter, returnDescriptor)</c> helper (or
/// <c>ResolveInline(mangledGetter)</c> for inline-class variants that
/// route through static <c>box-impl(I)L&lt;outer&gt;;</c>), and one
/// implementing partial property per declared getter.
/// </summary>
internal static class ComposeCompanionEmitter
{
    /// <summary>
    /// One companion-getter declaration, gathered from
    /// <c>[ComposeCompanionGetter]</c> on a <c>public static partial</c>
    /// property.
    /// </summary>
    public readonly struct Getter
    {
        public Getter(string propertyName, string returnTypeFullyQualified, string getterName, string? returnDescriptor)
        {
            PropertyName = propertyName;
            ReturnTypeFullyQualified = returnTypeFullyQualified;
            GetterName = getterName;
            ReturnDescriptor = returnDescriptor;
        }

        public string PropertyName { get; }
        /// <summary>e.g. <c>global::AndroidX.Compose.FontWeight</c>.</summary>
        public string ReturnTypeFullyQualified { get; }
        /// <summary>Kotlin getter name (e.g. <c>getThin</c> or <c>getCenter-e0LSkKk</c>).</summary>
        public string GetterName { get; }
        /// <summary>Override return descriptor (e.g. <c>Landroidx/.../SystemFontFamily;</c>); null = derive from outer.</summary>
        public string? ReturnDescriptor { get; }
    }

    public static string Emit(
        string? @namespace,
        string className,
        string outerJniClass,
        bool inlineClass,
        IReadOnlyList<Getter> getters)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by AndroidX.Compose.SourceGenerators.ComposeCompanionGenerator.");
        sb.AppendLine("// Mirrors the hand-written FindClass → GetStaticFieldID(Companion) → NewGlobalRef pattern");
        sb.AppendLine("// shared by FontWeight/TextDecoration/ContentScale/FontFamily/TextAlign/FontStyle.");
        sb.AppendLine("#nullable enable");
        if (@namespace is not null)
        {
            sb.Append("namespace ").Append(@namespace).AppendLine(";");
        }
        sb.AppendLine();

        sb.Append("partial class ").AppendLine(className);
        sb.AppendLine("{");

        // Companion field cache. NewGlobalRef-backed (process-lifetime) so the
        // boxed singleton stays addressable for every subsequent CallObjectMethod.
        sb.AppendLine("    static global::System.IntPtr s_companion;");

        if (inlineClass)
        {
            // box-impl static method ID lives on the outer class itself.
            sb.AppendLine("    static global::System.IntPtr s_box_method;");
        }
        sb.AppendLine();

        // Per-property cache fields. One nullable peer per declared getter.
        foreach (var g in getters)
        {
            sb.Append("    static ").Append(g.ReturnTypeFullyQualified)
              .Append("? s_").Append(CamelCase(g.PropertyName)).AppendLine(";");
        }
        sb.AppendLine();

        EmitCompanionAccessor(sb, outerJniClass);
        sb.AppendLine();

        if (inlineClass)
            EmitResolveInline(sb, className, outerJniClass);
        else
            EmitResolveSimple(sb, className);
        sb.AppendLine();

        EmitProperties(sb, outerJniClass, inlineClass, getters);

        sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitCompanionAccessor(StringBuilder sb, string outerJniClass)
    {
        sb.AppendLine("    static global::System.IntPtr Companion()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s_companion == global::System.IntPtr.Zero)");
        sb.AppendLine("        {");
        sb.Append("            global::System.IntPtr __outer = global::Android.Runtime.JNIEnv.FindClass(\"")
          .Append(outerJniClass).AppendLine("\");");
        sb.Append("            global::System.IntPtr __fid = global::Android.Runtime.JNIEnv.GetStaticFieldID(__outer, \"Companion\", \"L")
          .Append(outerJniClass).AppendLine("$Companion;\");");
        sb.AppendLine("            global::System.IntPtr __local = global::Android.Runtime.JNIEnv.GetStaticObjectField(__outer, __fid);");
        sb.AppendLine("            s_companion = global::Android.Runtime.JNIEnv.NewGlobalRef(__local);");
        sb.AppendLine("            global::Android.Runtime.JNIEnv.DeleteLocalRef(__local);");
        sb.AppendLine("        }");
        sb.AppendLine("        return s_companion;");
        sb.AppendLine("    }");
    }

    static void EmitResolveSimple(StringBuilder sb, string className)
    {
        sb.Append("    static ").Append(className).AppendLine(" ResolveSimple(string getterName, string returnDescriptor)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.IntPtr __cls = global::Android.Runtime.JNIEnv.FindClass(__companionJni);");
        sb.AppendLine("        global::System.IntPtr __mid = global::Android.Runtime.JNIEnv.GetMethodID(__cls, getterName, \"()\" + returnDescriptor);");
        sb.AppendLine("        global::System.IntPtr __value = global::Android.Runtime.JNIEnv.CallObjectMethod(Companion(), __mid);");
        sb.Append("        return new ").Append(className).AppendLine("(__value, global::Android.Runtime.JniHandleOwnership.TransferLocalRef);");
        sb.AppendLine("    }");
    }

    static void EmitResolveInline(StringBuilder sb, string className, string outerJniClass)
    {
        sb.Append("    static unsafe ").Append(className).AppendLine(" ResolveInline(string mangledGetter)");
        sb.AppendLine("    {");
        sb.AppendLine("        // 1. Companion.<getter>()I returns the packed int.");
        sb.AppendLine("        global::System.IntPtr __companionCls = global::Android.Runtime.JNIEnv.FindClass(__companionJni);");
        sb.AppendLine("        global::System.IntPtr __getter = global::Android.Runtime.JNIEnv.GetMethodID(__companionCls, mangledGetter, \"()I\");");
        sb.AppendLine("        int __packed = global::Android.Runtime.JNIEnv.CallIntMethod(Companion(), __getter);");
        sb.AppendLine();
        sb.AppendLine("        // 2. <Outer>.box-impl(int) -> L<Outer>; to materialize the boxed reference.");
        sb.Append("        global::System.IntPtr __outerCls = global::Android.Runtime.JNIEnv.FindClass(\"")
          .Append(outerJniClass).AppendLine("\");");
        sb.AppendLine("        if (s_box_method == global::System.IntPtr.Zero)");
        sb.Append("            s_box_method = global::Android.Runtime.JNIEnv.GetStaticMethodID(__outerCls, \"box-impl\", \"(I)L")
          .Append(outerJniClass).AppendLine(";\");");
        sb.AppendLine("        global::Android.Runtime.JValue* __args = stackalloc global::Android.Runtime.JValue[1];");
        sb.AppendLine("        __args[0] = new global::Android.Runtime.JValue(__packed);");
        sb.AppendLine("        global::System.IntPtr __boxed = global::Android.Runtime.JNIEnv.CallStaticObjectMethod(__outerCls, s_box_method, __args);");
        sb.Append("        return new ").Append(className).AppendLine("(__boxed, global::Android.Runtime.JniHandleOwnership.TransferLocalRef);");
        sb.AppendLine("    }");
    }

    static void EmitProperties(
        StringBuilder sb,
        string outerJniClass,
        bool inlineClass,
        IReadOnlyList<Getter> getters)
    {
        // Embed the companion-JNI string once as a private const so both
        // Resolve helpers and the (hypothetical) future call sites stay
        // in sync without repeating the literal.
        sb.Append("    const string __companionJni = \"").Append(outerJniClass).AppendLine("$Companion\";");
        sb.AppendLine();

        foreach (var g in getters)
        {
            var cacheField = "s_" + CamelCase(g.PropertyName);
            sb.Append("    public static partial ").Append(g.ReturnTypeFullyQualified).Append(' ')
              .Append(g.PropertyName).Append(" => ").Append(cacheField).Append(" ??= ");

            if (inlineClass)
            {
                sb.Append("ResolveInline(\"").Append(EscapeForString(g.GetterName)).AppendLine("\");");
            }
            else
            {
                var returnDescriptor = g.ReturnDescriptor ?? ("L" + outerJniClass + ";");
                sb.Append("ResolveSimple(\"").Append(EscapeForString(g.GetterName))
                  .Append("\", \"").Append(EscapeForString(returnDescriptor)).AppendLine("\");");
            }
        }
    }

    static string CamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        if (char.IsLower(name[0])) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    static string EscapeForString(string raw)
    {
        // Companion getter strings come from C# attribute arguments, which
        // already round-trip through C# string escaping. The only way an
        // illegal character lands here is a backslash or a double quote in
        // the source attribute, neither of which is plausible for JNI
        // method names or descriptors. Keep the escape conservative.
        if (raw.IndexOf('\\') < 0 && raw.IndexOf('"') < 0) return raw;
        return raw.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
