using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Microsoft.AndroidX.Compose.SourceGenerators;

internal static class ComposeDefaultsEmitter
{
    /// <summary>
    /// One bit position in the generated enum.
    /// <see cref="EnumMember"/> is null when the bit is consumed (occupies
    /// a position) but no member is emitted — e.g. params the caller always
    /// provides, or Kotlin lambda content slots.
    /// </summary>
    public readonly struct Slot
    {
        public Slot(int bit, string? enumMember, string rawName, string? skipReason)
        {
            Bit = bit;
            EnumMember = enumMember;
            RawName = rawName;
            SkipReason = skipReason;
        }

        public int Bit { get; }
        public string? EnumMember { get; }
        public string RawName { get; }
        public string? SkipReason { get; }
    }

    /// <summary>Build slots from a Roslyn method symbol (generic attribute path).</summary>
    public static IReadOnlyList<Slot> SlotsFromSymbol(IMethodSymbol method, int composerIndex)
    {
        var slots = new List<Slot>(composerIndex);
        for (int i = 0; i < composerIndex; i++)
        {
            var p = method.Parameters[i];
            if (ComposeDefaultsGenerator.IsKotlinFunction(p.Type))
            {
                slots.Add(new Slot(i, null, p.Name, $"{p.Type.Name} — always provided, no enum member."));
                continue;
            }
            slots.Add(new Slot(i, PascalCase(p.Name, i), p.Name, null));
        }
        return slots;
    }

    /// <summary>Build slots from a positional name list (declarative attribute path).</summary>
    public static IReadOnlyList<Slot> SlotsFromNames(IReadOnlyList<string> names)
    {
        var slots = new List<Slot>(names.Count);
        for (int i = 0; i < names.Count; i++)
        {
            var raw = names[i] ?? string.Empty;
            if (raw.Length > 0 && raw[0] == '!')
            {
                var inner = raw.Substring(1);
                slots.Add(new Slot(i, null, inner, "marked '!' — always provided, no enum member."));
            }
            else
            {
                slots.Add(new Slot(i, PascalCase(raw, i), raw, null));
            }
        }
        return slots;
    }

    public static string Emit(string enumName, string sourceComment, IReadOnlyList<Slot> slots)
    {
        var members = slots.Where(s => s.EnumMember is not null).ToList();

        // Kotlin lowers > 32-slot $default bitmasks into a pair of int
        // values (II at the JVM boundary). To keep a single enum that
        // can model every bit position without `1 << 32` silently
        // wrapping to bit 0, switch to a long-backed enum once we
        // exceed 31 positional slots. ≤ 31 slots stay byte-for-byte
        // identical to the pre-issue-#178 output.
        bool useLong = slots.Count > 31;
        string shiftSuffix = useLong ? "L" : "";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.Append("// Generated by Microsoft.AndroidX.Compose.SourceGenerators from ");
        sb.AppendLine(sourceComment);
        sb.AppendLine("// Bit positions match the Kotlin parameter index in the $default bitmask.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Microsoft.AndroidX.Compose");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Flags]");
        sb.Append("    internal enum ").Append(enumName);
        if (useLong)
            sb.AppendLine(" : long");
        else
            sb.AppendLine();
        sb.AppendLine("    {");
        sb.AppendLine("        None = 0,");

        int maxNameLen = members.Count == 0 ? 0 : members.Max(m => m.EnumMember!.Length);
        foreach (var slot in members)
        {
            sb.Append("        ").Append(slot.EnumMember).Append(' ', maxNameLen - slot.EnumMember!.Length)
              .Append(" = 1").Append(shiftSuffix).Append(" << ").Append(slot.Bit).AppendLine(",");
        }

        foreach (var slot in slots)
        {
            if (slot.EnumMember is not null) continue;
            sb.Append("        // bit ").Append(slot.Bit).Append(": ").Append(slot.RawName)
              .Append(" — ").AppendLine(slot.SkipReason ?? "skipped.");
        }

        sb.AppendLine();
        sb.AppendLine("        /// <summary>OR of every user-defaultable bit.</summary>");
        if (members.Count == 0)
        {
            sb.AppendLine("        All = 0,");
        }
        else
        {
            sb.Append("        All = ");
            sb.Append(string.Join(" | ", members.Select(m => m.EnumMember)));
            sb.AppendLine(",");
        }
        sb.AppendLine("    }");

        if (useLong)
        {
            sb.AppendLine();
            sb.Append("    /// <summary>Helpers for the long-backed <c>").Append(enumName).AppendLine("</c> mask.</summary>");
            sb.Append("    internal static class ").Append(enumName).AppendLine("Extensions");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Split a long-backed default mask into the pair of <c>int</c>");
            sb.AppendLine("        /// values Kotlin's <c>$default</c> trampolines expect when the");
            sb.AppendLine("        /// bit count exceeds 32 (low 32 bits → <c>Mask0</c>, high 32 bits → <c>Mask1</c>).");
            sb.AppendLine("        /// </summary>");
            sb.Append("        public static (int Mask0, int Mask1) Split(this ").Append(enumName).AppendLine(" value) =>");
            sb.AppendLine("            ((int)((long)value & 0xFFFFFFFFL), (int)(((long)value >> 32) & 0xFFFFFFFFL));");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    static string PascalCase(string raw, int positionFallback)
    {
        if (string.IsNullOrEmpty(raw))
            return "Param" + positionFallback;

        if (raw.Length >= 2 && raw[0] == 'p' && IsAllDigits(raw, 1))
            return "Param" + raw.Substring(1);

        if (char.IsUpper(raw[0]))
            return raw;

        return char.ToUpperInvariant(raw[0]) + raw.Substring(1);
    }

    static bool IsAllDigits(string s, int start)
    {
        for (int i = start; i < s.Length; i++)
            if (!char.IsDigit(s[i])) return false;
        return start < s.Length;
    }
}

