using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace AndroidX.Compose.SourceGenerators;

/// <summary>
/// Emits ambient-composer siblings for explicit-composer adapter methods.
/// The hand-written method remains the single rendering implementation.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ImplicitComposableOverloadGenerator : IIncrementalGenerator
{
    const string AttributeMetadataName =
        "AndroidX.Compose.GenerateImplicitComposableAttribute";
    const string ComposableAttributeMetadataName =
        "AndroidX.Compose.ComposableAttribute";
    const string ComposableContentAttributeMetadataName =
        "AndroidX.Compose.ComposableContentAttribute";
    const string ComposablesMetadataName = "AndroidX.Compose.Composables";
    const string ComposerMetadataName = "AndroidX.Compose.Runtime.IComposer";

    static readonly SymbolDisplayFormat TypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions
            | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
            | SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeMetadataName,
                predicate: static (node, _) =>
                    node is Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax,
                transform: static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol)
            .Collect();

        context.RegisterSourceOutput(methods, static (spc, candidates) =>
        {
            if (candidates.IsDefaultOrEmpty)
                return;

            var valid = new List<MethodModel>();
            foreach (var method in candidates)
            {
                var model = BuildModel(method, out var error);
                if (model is null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.ImplicitComposableGenerationInvalid,
                        method.Locations.FirstOrDefault() ?? Location.None,
                        method.ToDisplayString(),
                        error ?? "unknown shape"));
                    continue;
                }
                valid.Add(model);
            }

            if (valid.Count == 0)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace AndroidX.Compose");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class Composables");
            sb.AppendLine("    {");
            foreach (var model in valid.OrderBy(
                         static m => m.Method.Name,
                         StringComparer.Ordinal))
            {
                EmitMethod(sb, model);
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource(
                "Microsoft.AndroidX.Compose.ImplicitComposableOverloads.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    static MethodModel? BuildModel(IMethodSymbol method, out string? error)
    {
        error = null;
        if (!method.IsStatic || method.ReturnsVoid == false)
        {
            error = "the source method must be static and return void";
            return null;
        }
        if (method.DeclaredAccessibility is not (
                Accessibility.Public or Accessibility.Internal))
        {
            error = "the source method must be public or internal";
            return null;
        }
        if (method.ContainingType.ToDisplayString() != ComposablesMetadataName)
        {
            error = "the source method must be declared on AndroidX.Compose.Composables";
            return null;
        }
        if (!HasAttribute(method, ComposableAttributeMetadataName))
        {
            error = "the source method must also carry [Composable]";
            return null;
        }
        if (method.IsGenericMethod)
        {
            error = "generic source methods are not yet supported";
            return null;
        }
        if (method.Parameters.Length == 0
            || !IsComposer(method.Parameters[0].Type)
            || method.Parameters.Skip(1).Any(static p => IsComposer(p.Type)))
        {
            error = "the first and only IComposer parameter must be parameter zero";
            return null;
        }

        var parameters = new List<ParameterModel>();
        foreach (var parameter in method.Parameters.Skip(1))
        {
            if (parameter.RefKind != RefKind.None)
            {
                error = $"parameter '{parameter.Name}' cannot use ref, out, or in";
                return null;
            }

            bool composableContent = HasAttribute(
                parameter,
                ComposableContentAttributeMetadataName);
            if (!composableContent)
            {
                parameters.Add(new ParameterModel(
                    parameter,
                    parameter.Type.ToDisplayString(TypeFormat),
                    adapterArity: -1));
                continue;
            }

            if (parameter.Type is not INamedTypeSymbol action
                || action.OriginalDefinition.ContainingNamespace.ToDisplayString()
                    != "System"
                || action.Name != "Action"
                || action.TypeArguments.Length == 0
                || !IsComposer(action.TypeArguments[action.TypeArguments.Length - 1]))
            {
                error =
                    $"[ComposableContent] parameter '{parameter.Name}' must be System.Action<..., IComposer>";
                return null;
            }

            int adapterArity = action.TypeArguments.Length - 1;
            string implicitType = adapterArity == 0
                ? "global::System.Action"
                : "global::System.Action<"
                    + string.Join(", ", action.TypeArguments
                        .Take(adapterArity)
                        .Select(static t => t.ToDisplayString(TypeFormat)))
                    + ">";
            if (parameter.NullableAnnotation == NullableAnnotation.Annotated)
                implicitType += "?";

            parameters.Add(new ParameterModel(
                parameter,
                implicitType,
                adapterArity));
        }

        return new MethodModel(method, parameters);
    }

    static void EmitMethod(StringBuilder sb, MethodModel model)
    {
        var method = model.Method;
        sb.AppendLine();
        sb.Append("        /// <summary>Ambient-composer overload for <c>")
          .Append(method.Name)
          .AppendLine("</c>.</summary>");
        EmitObsoleteAttribute(sb, method);
        sb.AppendLine("        [global::AndroidX.Compose.ComposableAttribute]");
        sb.Append("        public static void ")
          .Append(EscapeIdentifier(method.Name))
          .Append('(');
        for (int i = 0; i < model.Parameters.Count; i++)
        {
            if (i > 0)
                sb.Append(", ");
            var parameter = model.Parameters[i];
            if (parameter.AdapterArity >= 0)
            {
                sb.Append("[global::AndroidX.Compose.ComposableContentAttribute] ");
            }
            sb.Append(parameter.ImplicitType)
              .Append(' ')
              .Append(EscapeIdentifier(parameter.Symbol.Name));
            AppendDefaultValue(sb, parameter.Symbol);
        }
        sb.AppendLine(")");
        sb.AppendLine("        {");
        sb.Append("            ")
          .Append(EscapeIdentifier(method.Name))
          .AppendLine("(");
        sb.Append("                global::AndroidX.Compose.ComposableContext.Current");
        sb.AppendLine(model.Parameters.Count == 0 ? ");" : ",");
        for (int i = 0; i < model.Parameters.Count; i++)
        {
            var parameter = model.Parameters[i];
            sb.Append("                ");
            EmitArgument(sb, parameter);
            sb.AppendLine(i == model.Parameters.Count - 1 ? ");" : ",");
        }
        sb.AppendLine("        }");
    }

    static void EmitObsoleteAttribute(StringBuilder sb, IMethodSymbol method)
    {
        var obsolete = method.GetAttributes().FirstOrDefault(static attribute =>
            attribute.AttributeClass?.ToDisplayString()
                == "System.ObsoleteAttribute");
        if (obsolete is null)
            return;

        sb.Append("        [global::System.ObsoleteAttribute(");
        bool hasArgument = false;
        if (obsolete.ConstructorArguments.Length > 0)
        {
            if (obsolete.ConstructorArguments[0].Value is string message)
                sb.Append(SymbolDisplay.FormatLiteral(message, quote: true));
            else
                sb.Append("null");
            hasArgument = true;
        }
        if (obsolete.ConstructorArguments.Length > 1
            && obsolete.ConstructorArguments[1].Value is bool error)
        {
            if (hasArgument)
                sb.Append(", ");
            sb.Append(error ? "true" : "false");
            hasArgument = true;
        }
        foreach (var named in obsolete.NamedArguments)
        {
            if (named.Key is not ("DiagnosticId" or "UrlFormat")
                || named.Value.Value is not string value)
            {
                continue;
            }

            if (hasArgument)
                sb.Append(", ");
            sb.Append(named.Key)
              .Append(" = ")
              .Append(SymbolDisplay.FormatLiteral(value, quote: true));
            hasArgument = true;
        }
        sb.AppendLine(")]");
    }

    static void EmitArgument(StringBuilder sb, ParameterModel parameter)
    {
        string name = EscapeIdentifier(parameter.Symbol.Name);
        if (parameter.AdapterArity < 0)
        {
            sb.Append(name);
            return;
        }

        bool nullable =
            parameter.Symbol.NullableAnnotation == NullableAnnotation.Annotated;
        if (nullable)
            sb.Append(name).Append(" is null ? null : ");

        sb.Append('(');
        for (int i = 0; i < parameter.AdapterArity; i++)
        {
            if (i > 0)
                sb.Append(", ");
            sb.Append("__p").Append(i.ToString(CultureInfo.InvariantCulture));
        }
        if (parameter.AdapterArity > 0)
            sb.Append(", ");
        sb.Append("__composer) => ").Append(name).Append('(');
        for (int i = 0; i < parameter.AdapterArity; i++)
        {
            if (i > 0)
                sb.Append(", ");
            sb.Append("__p").Append(i.ToString(CultureInfo.InvariantCulture));
        }
        sb.Append(')');
    }

    static void AppendDefaultValue(StringBuilder sb, IParameterSymbol parameter)
    {
        if (!parameter.HasExplicitDefaultValue)
            return;

        sb.Append(" = ");
        object? value = parameter.ExplicitDefaultValue;
        if (value is null)
        {
            if (parameter.Type.IsValueType
                && parameter.Type.OriginalDefinition.SpecialType
                    != SpecialType.System_Nullable_T)
            {
                sb.Append("default(")
                  .Append(parameter.Type.ToDisplayString(TypeFormat))
                  .Append(')');
            }
            else
            {
                sb.Append("null");
            }
        }
        else if (parameter.Type.TypeKind == TypeKind.Enum)
        {
            sb.Append('(')
              .Append(parameter.Type.ToDisplayString(TypeFormat))
              .Append(')')
              .Append(Convert.ToString(value, CultureInfo.InvariantCulture));
        }
        else if (value is bool boolean)
        {
            sb.Append(boolean ? "true" : "false");
        }
        else if (value is string text)
        {
            sb.Append(SymbolDisplay.FormatLiteral(text, quote: true));
        }
        else if (value is char character)
        {
            sb.Append(SymbolDisplay.FormatLiteral(character, quote: true));
        }
        else if (value is float single)
        {
            if (float.IsNaN(single))
                sb.Append("global::System.Single.NaN");
            else if (float.IsPositiveInfinity(single))
                sb.Append("global::System.Single.PositiveInfinity");
            else if (float.IsNegativeInfinity(single))
                sb.Append("global::System.Single.NegativeInfinity");
            else
                sb.Append(single.ToString("R", CultureInfo.InvariantCulture))
                  .Append('F');
        }
        else if (value is double dbl)
        {
            if (double.IsNaN(dbl))
                sb.Append("global::System.Double.NaN");
            else if (double.IsPositiveInfinity(dbl))
                sb.Append("global::System.Double.PositiveInfinity");
            else if (double.IsNegativeInfinity(dbl))
                sb.Append("global::System.Double.NegativeInfinity");
            else
                sb.Append(dbl.ToString("R", CultureInfo.InvariantCulture));
        }
        else if (value is decimal dec)
        {
            sb.Append(dec.ToString(CultureInfo.InvariantCulture)).Append('M');
        }
        else if (value is uint unsigned)
        {
            sb.Append(unsigned.ToString(CultureInfo.InvariantCulture)).Append('U');
        }
        else if (value is long signedLong)
        {
            sb.Append(signedLong.ToString(CultureInfo.InvariantCulture)).Append('L');
        }
        else if (value is ulong unsignedLong)
        {
            sb.Append(unsignedLong.ToString(CultureInfo.InvariantCulture))
              .Append("UL");
        }
        else
        {
            sb.Append(Convert.ToString(value, CultureInfo.InvariantCulture));
        }
    }

    static bool IsComposer(ITypeSymbol type) =>
        type.ToDisplayString() == ComposerMetadataName;

    static bool HasAttribute(ISymbol symbol, string metadataName) =>
        symbol.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == metadataName);

    static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None
            || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;

    sealed class MethodModel
    {
        public MethodModel(
            IMethodSymbol method,
            IReadOnlyList<ParameterModel> parameters)
        {
            Method = method;
            Parameters = parameters;
        }

        public IMethodSymbol Method { get; }
        public IReadOnlyList<ParameterModel> Parameters { get; }
    }

    sealed class ParameterModel
    {
        public ParameterModel(
            IParameterSymbol symbol,
            string implicitType,
            int adapterArity)
        {
            Symbol = symbol;
            ImplicitType = implicitType;
            AdapterArity = adapterArity;
        }

        public IParameterSymbol Symbol { get; }
        public string ImplicitType { get; }
        public int AdapterArity { get; }
    }
}
