namespace ComposeNet.SourceGenerators;

/// <summary>
/// Source text added to the user's compilation via
/// <see cref="Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput"/>.
/// </summary>
internal static class Attributes
{
    public const string Source = """
        // <auto-generated/>
        #nullable enable
        namespace ComposeNet
        {
            /// <summary>
            /// Apply at assembly scope to generate a named-bit
            /// <c>[Flags] internal enum &lt;EnumName&gt;</c> from the
            /// parameter shape of <typeparamref name="T"/>'s static
            /// method <paramref name="methodName"/>. Bit numbers match
            /// the Kotlin parameter index in the bytecode — the position
            /// the <c>$default</c> bitmask expects.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly,
                                           AllowMultiple = true)]
            internal sealed class ComposeDefaultsAttribute<T> : global::System.Attribute
            {
                public ComposeDefaultsAttribute(string methodName, string enumName) { }
            }
        }
        """;
}
