namespace ComposeNet.SourceGenerators;

/// <summary>
/// Source text added to the user's compilation via
/// <see cref="Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput"/>.
/// </summary>
internal static class Attributes
{
    public const string Source = """
        // <auto-generated/>
        #nullable enable
        namespace ComposeNet
        {
            /// <summary>
            /// Apply at assembly scope to generate a named-bit
            /// <c>[Flags] internal enum &lt;EnumName&gt;</c> from the
            /// parameter shape of <typeparamref name="T"/>'s static
            /// method named by the constructor's <c>methodName</c>
            /// argument. Bit numbers match the Kotlin parameter index
            /// in the bytecode — the position the <c>$default</c>
            /// bitmask expects.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly,
                                           AllowMultiple = true)]
            internal sealed class ComposeDefaultsAttribute<T> : global::System.Attribute
            {
                public ComposeDefaultsAttribute(string methodName, string enumName) { }
            }

            /// <summary>
            /// Apply at assembly scope to generate a named-bit
            /// <c>[Flags] internal enum &lt;EnumName&gt;</c> from an
            /// explicit positional parameter list. Use this overload
            /// when the Kotlin <c>$default</c>-bearing overload was
            /// stripped from the binding (mangled JVM name, inline-class
            /// param, etc.) and there is no <c>IMethodSymbol</c> to read.
            /// Each name occupies one bit at its index; prefix a name
            /// with <c>!</c> to consume the bit without emitting an
            /// enum member (e.g. params the caller always provides).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly,
                                           AllowMultiple = true)]
            internal sealed class ComposeDefaultsAttribute : global::System.Attribute
            {
                public ComposeDefaultsAttribute(string enumName, params string[] parameterNames) { }
            }

            /// <summary>
            /// Apply to a <c>partial</c> static method on
            /// <c>ComposeBridges</c> to have ComposeNet.SourceGenerators
            /// emit its JNI-bridge body. The partial method declares the
            /// user-facing C# signature; the generator fills in cache
            /// fields, lazy class/method ID resolution, the JValue array,
            /// the <c>$default</c> bitmask, and the
            /// <c>try</c>/<c>finally</c> + <c>GC.KeepAlive</c> block.
            /// </summary>
            /// <remarks>
            /// <para><b>Class</b>: JNI-internal class name, e.g.
            /// <c>androidx/compose/material3/ButtonKt</c>.</para>
            /// <para><b>JvmName</b>: the (often mangled) Kotlin-emitted
            /// method name, e.g. <c>Button</c> or <c>Surface-T9BRK9s</c>.</para>
            /// <para><b>Signature</b>: full JNI signature string for the
            /// underlying static method. Ends in
            /// <c>...Composer;I*I)&lt;ReturnType&gt;</c> (one trailing
            /// <c>I</c> per <c>$changed</c> group plus one for
            /// <c>$default</c>) when the function has at least one
            /// defaultable parameter, or <c>...Composer;I*)&lt;ReturnType&gt;</c>
            /// when every parameter is required (no <c>$default</c> slot
            /// in the bytecode). The return-type token is <c>V</c> for
            /// <c>void</c> bridges or an <c>L...;</c> for state holders /
            /// factories.</para>
            /// <para><b>Defaults</b>: <c>typeof(XxxDefault)</c> — the
            /// <c>$default</c> bitmask enum produced by
            /// <see cref="ComposeDefaultsAttribute"/>. The generator reads
            /// the matching declarative <c>[ComposeDefaults(...)]</c>
            /// attribute to learn the Kotlin parameter names + bit
            /// positions. Required when the JNI signature has a
            /// <c>$default</c> slot; must be omitted otherwise. The
            /// generator cross-checks this against the signature and
            /// reports CN2005 on a mismatch.</para>
            /// <para><b>InstanceField</b>: when set, the bridge calls an
            /// instance method on a Kotlin <c>object</c> singleton — name
            /// the <c>$$INSTANCE</c>-style static field
            /// (e.g. <c>INSTANCE</c>) and the generator emits
            /// <c>GetMethodID</c> + <c>CallObjectMethod</c> instead.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method,
                                           AllowMultiple = false)]
            internal sealed class ComposeBridgeAttribute : global::System.Attribute
            {
                public ComposeBridgeAttribute() { }
                public string Class { get; set; } = "";
                public string JvmName { get; set; } = "";
                public string Signature { get; set; } = "";
                public global::System.Type? Defaults { get; set; }
                public string? InstanceField { get; set; }
            }

            /// <summary>
            /// Apply alongside <see cref="ComposeBridgeAttribute"/> on a
            /// <c>partial</c> method in <c>ComposeBridges</c> to have
            /// <c>ComposeFacadeGenerator</c> emit the corresponding
            /// user-facing facade class (a <c>public sealed partial</c>
            /// <see cref="ComposableNode"/> / <see cref="ComposableContainer"/>
            /// in <c>namespace ComposeNet</c>).
            /// </summary>
            /// <remarks>
            /// The facade's constructor, base class, and <c>Render</c> body
            /// are inferred from the bridge's C# parameter shape:
            /// <list type="bullet">
            /// <item><description><c>IModifier? modifier</c> → render uses
            /// <c>BuildModifier()</c>; no ctor param.</description></item>
            /// <item><description><c>IFunction0 &lt;name&gt;</c> → ctor takes
            /// <c>System.Action &lt;name&gt;</c>; render wraps in
            /// <c>ComposableLambda0</c>.</description></item>
            /// <item><description><c>IFunction2 content</c> /
            /// <c>IFunction3 content</c> → container shape, base
            /// <c>ComposableContainer</c>; render uses
            /// <c>ComposableLambdas.Wrap2</c> / <c>Wrap3</c>.</description></item>
            /// <item><description>Primitive (<c>string</c>, <c>int</c>,
            /// <c>long</c>, <c>bool</c>, <c>float</c>, <c>double</c>) →
            /// positional ctor parameter.</description></item>
            /// </list>
            /// Anything else (e.g. <c>IFunction1</c> callbacks, value-class
            /// handles, the caller-controlled <c>int defaults</c> hatch) is
            /// rejected via diagnostic CN3002 — leave that bridge hand-written.
            /// <para><b>Docs &amp; overrides:</b> the generated class is
            /// <c>sealed partial</c>. Add a sibling stub
            /// <c>src/ComposeNet.Compose/&lt;Name&gt;.cs</c> with the
            /// <c>///&lt;summary&gt;</c> comment (and any extra members
            /// the facade needs) — the generator deliberately does not
            /// emit a summary so the stub owns it.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method,
                                           AllowMultiple = false)]
            internal sealed class ComposeFacadeAttribute : global::System.Attribute
            {
                public ComposeFacadeAttribute() { }

                /// <summary>Optional override for the generated class name. Defaults to the bridge method name.</summary>
                public string? ClassName { get; set; }

                /// <summary>
                /// Optional scope to publish from an <c>IFunction3</c> content
                /// lambda. <c>"Row"</c> (e.g. <see cref="NavigationBar"/>,
                /// <see cref="Badge"/>) or <c>"Column"</c>. The lambda
                /// receives the scope handle and pushes it via
                /// <c>RenderContext.PushScope(scope, ScopeKind.X)</c> so
                /// child composables can read it. Requires a bridge with
                /// an <c>IFunction3 content</c> parameter.
                /// </summary>
                public string? Scope { get; set; }

                /// <summary>
                /// Phase 6 — name of a <c>ColorScheme</c> property (e.g.
                /// <c>"secondaryContainer"</c>) to use as a runtime fallback
                /// when the user leaves the bridge's container-color
                /// parameter at its sentinel <c>0L</c>. The generator
                /// emits a <c>long ContainerColor { get; set; }</c>
                /// property and binds the named bridge param (see
                /// <see cref="ColorParameter"/>) to
                /// <c>ContainerColor != 0L ? ContainerColor :
                /// MaterialTheme.Instance.GetColorScheme(composer,0).&lt;Slot&gt;</c>.
                /// </summary>
                public string? DefaultColorFromTheme { get; set; }

                /// <summary>
                /// Phase 6 — the name of the bridge's <c>long</c>
                /// parameter that <see cref="DefaultColorFromTheme"/>
                /// targets. Optional when the bridge has exactly one
                /// <c>long</c> user parameter; required when there's
                /// ambiguity.
                /// </summary>
                public string? ColorParameter { get; set; }

                /// <summary>
                /// Phase 8 — fallback for the <c>$default</c> enum when
                /// the facade method has no paired
                /// <see cref="ComposeBridgeAttribute"/>. Used by tiny
                /// pass-through "wrapper" bridges (extended partial methods
                /// with hand-written bodies that delegate straight to a
                /// bound binding instead of doing JNI). Set this to
                /// <c>typeof(XxxDefault)</c> to drive the auto-mask logic
                /// for direct-binding facades. Bridge-mode facades read
                /// <c>Defaults</c> from their <c>[ComposeBridge]</c>
                /// instead — this property is ignored in that case.
                /// </summary>
                public global::System.Type? Defaults { get; set; }
            }

            /// <summary>
            /// Phase 3 — apply to a Kotlin-function bridge parameter to
            /// override the C# property name the facade exposes for that
            /// slot. Default is the parameter name PascalCased. Useful
            /// when the Kotlin name reads awkwardly in C# (e.g.
            /// <c>content</c> → <c>Body</c>,
            /// <c>headlineContent</c> → <c>Headline</c>,
            /// <c>tooltip</c> → <c>Tip</c>).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter,
                                           AllowMultiple = false)]
            internal sealed class SlotAttribute : global::System.Attribute
            {
                public SlotAttribute(string propertyName) { }
            }

            /// <summary>
            /// Phase 2 — apply to an <c>IFunction1</c> bridge parameter
            /// to mark it as a typed C# callback. The facade gets an
            /// <c>Action&lt;T&gt;</c> ctor parameter; the generated
            /// <c>Render</c> body wraps it in a <c>ComposableLambda1</c>
            /// that un-boxes the Kotlin value for <c>T</c>.
            /// Supported <c>T</c>: <c>bool</c>, <c>string</c>, <c>float</c>.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter,
                                           AllowMultiple = false)]
            internal sealed class CallbackAttribute : global::System.Attribute
            {
                public CallbackAttribute(global::System.Type valueType) { }
            }

            /// <summary>
            /// Phase 7 — apply to the <c>IntPtr</c> bridge parameter
            /// that takes the resolved <c>Painter</c> handle. The facade
            /// replaces this parameter with a synthetic ctor argument
            /// <c>int drawableResourceId</c>; <c>Render</c> calls
            /// <c>ComposeBridges.PainterResource(id, composer)</c> to
            /// resolve the handle, forwards it to the annotated
            /// parameter, and wraps the bridge invocation in
            /// <c>try</c> / <c>finally</c> + <c>JNIEnv.DeleteLocalRef</c>.
            /// At most one bridge parameter may carry <c>[PainterResource]</c>.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter,
                                           AllowMultiple = false)]
            internal sealed class PainterResourceAttribute : global::System.Attribute
            {
                public PainterResourceAttribute() { }
            }

            /// <summary>
            /// Phase 4 — apply to the <c>IntPtr</c> bridge parameter that
            /// carries a Kotlin state-holder handle (e.g.
            /// <c>DatePickerState</c>, <c>DateRangePickerState</c>). The
            /// facade calls the named <c>Remember*State</c> bridge on
            /// <c>ComposeBridges</c> to resolve the handle, optionally
            /// binds it to a caller-supplied wrapper of type
            /// <see cref="StateType"/>, and forwards the handle to this
            /// parameter. The wrapper is exposed as a defaulted ctor
            /// argument (<c>StateType? state = null</c>).
            /// </summary>
            /// <remarks>
            /// <para><b>Remember</b>: the <c>nameof(ComposeBridges.X)</c>
            /// of a static partial bridge on <c>ComposeBridges</c> whose
            /// last parameter is an <c>IComposer</c> and that returns
            /// <c>IntPtr</c>. The remaining (leading) parameters are
            /// treated as init values — each one is read off the
            /// caller-supplied <c>StateType</c> wrapper at render time.
            /// Phase 4 covers the zero-user-param shape (e.g.
            /// <c>RememberDatePickerState(IComposer) -&gt; IntPtr</c>);
            /// Phase 4b adds support for parameterised remembers (e.g.
            /// <c>RememberTimePickerState(int, int, bool, IComposer)</c>).
            /// Each Remember user param must resolve to a readable
            /// instance member on <see cref="StateType"/>: the generator
            /// looks up the PascalCased name first (e.g.
            /// <c>initialHour</c> → <c>InitialHour</c>) and falls back
            /// to <c>Initial&lt;PascalCase&gt;</c> for the Kotlin
            /// convention where <c>initialX</c> remember args correspond
            /// to live wrapper property <c>X</c>.</para>
            /// <para><b>StateType</b>: the C# wrapper class that exposes
            /// the state-holder's properties. It must declare an
            /// instance, writable, non-readonly field named <c>Jvm</c>
            /// whose declared type is the binding-generated interface
            /// (e.g. <c>IDatePickerState</c>) — the generator emits
            /// <c>state.Jvm = Java.Lang.Object.GetObject&lt;IXxxState&gt;
            /// (handle, JniHandleOwnership.DoNotTransfer)!</c> the first
            /// time <c>Render</c> sees a non-null wrapper. For Phase 4b
            /// (parameterised Remember) the type must also be
            /// constructible with no arguments (parameterless ctor or
            /// all-defaulted-params ctor) so the facade can auto-create
            /// a default wrapper when the caller passes <c>null</c>.</para>
            /// <para><b>SharedState</b> (Phase 4c): when <c>true</c>,
            /// the generated <c>Render</c> preamble checks whether
            /// <c>_state.Jvm</c> is already populated (from an earlier
            /// sibling render that received the same wrapper instance)
            /// and skips the <c>RememberXxxState</c> call in that case,
            /// reusing the cached JNI handle directly. This lets two or
            /// more sibling facades share the same state-holder peer
            /// (e.g. a <see cref="TimePicker"/> and a
            /// <see cref="TimeInput"/> driven by the same
            /// <see cref="TimePickerState"/>). Defaults to <c>false</c>
            /// — every render calls Remember and Compose's slot-table
            /// caches per-call-site. Opt in only when the facade is
            /// designed to be paired with at least one sibling that
            /// uses the same <see cref="StateType"/>.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter,
                                           AllowMultiple = false)]
            internal sealed class StateHolderAttribute : global::System.Attribute
            {
                public StateHolderAttribute() { }
                public string Remember { get; set; } = "";
                public global::System.Type StateType { get; set; } = null!;
                public bool SharedState { get; set; }
            }
        }
        """;
}
