namespace ComposeNet.SourceGenerators;

/// <summary>
/// Source text added to the user's compilation via
/// <see cref="Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput"/>.
/// </summary>
internal static class Attributes
{
    public const string Source = """
        // <auto-generated/>
        #nullable enable
        namespace ComposeNet
        {
            /// <summary>
            /// Apply at assembly scope to generate a named-bit
            /// <c>[Flags] internal enum &lt;EnumName&gt;</c> from the
            /// parameter shape of <typeparamref name="T"/>'s static
            /// method <paramref name="methodName"/>. Bit numbers match
            /// the Kotlin parameter index in the bytecode — the position
            /// the <c>$default</c> bitmask expects.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly,
                                           AllowMultiple = true)]
            internal sealed class ComposeDefaultsAttribute<T> : global::System.Attribute
            {
                public ComposeDefaultsAttribute(string methodName, string enumName) { }
            }

            /// <summary>
            /// Apply at assembly scope to generate a named-bit
            /// <c>[Flags] internal enum &lt;EnumName&gt;</c> from an
            /// explicit positional parameter list. Use this overload
            /// when the Kotlin <c>$default</c>-bearing overload was
            /// stripped from the binding (mangled JVM name, inline-class
            /// param, etc.) and there is no <c>IMethodSymbol</c> to read.
            /// Each name occupies one bit at its index; prefix a name
            /// with <c>!</c> to consume the bit without emitting an
            /// enum member (e.g. params the caller always provides).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly,
                                           AllowMultiple = true)]
            internal sealed class ComposeDefaultsAttribute : global::System.Attribute
            {
                public ComposeDefaultsAttribute(string enumName, params string[] parameterNames) { }
            }

            /// <summary>
            /// Apply to a <c>partial</c> static method on
            /// <c>ComposeBridges</c> to have ComposeNet.SourceGenerators
            /// emit its JNI-bridge body. The partial method declares the
            /// user-facing C# signature; the generator fills in cache
            /// fields, lazy class/method ID resolution, the JValue array,
            /// the <c>$default</c> bitmask, and the
            /// <c>try</c>/<c>finally</c> + <c>GC.KeepAlive</c> block.
            /// </summary>
            /// <remarks>
            /// <para><b>Class</b>: JNI-internal class name, e.g.
            /// <c>androidx/compose/material3/ButtonKt</c>.</para>
            /// <para><b>JvmName</b>: the (often mangled) Kotlin-emitted
            /// method name, e.g. <c>Button</c> or <c>Surface-T9BRK9s</c>.</para>
            /// <para><b>Signature</b>: full JNI signature string for the
            /// underlying static method, ending in
            /// <c>...Composer;I*I)V</c> (one trailing <c>I</c> per
            /// <c>$changed</c> slot, then one for <c>$default</c>) or
            /// <c>...Composer;I*)V</c> when <b>Defaults</b> is omitted —
            /// <c>$default</c> only exists in the bytecode when at least
            /// one Kotlin parameter has a default value.</para>
            /// <para><b>Defaults</b>: <c>typeof(XxxDefault)</c> — the
            /// <c>$default</c> bitmask enum produced by
            /// <see cref="ComposeDefaultsAttribute"/>. The generator reads
            /// the matching declarative <c>[ComposeDefaults(...)]</c>
            /// attribute to learn the Kotlin parameter names + bit
            /// positions. Omit when the underlying <c>@Composable</c>
            /// has no defaultable parameters (no <c>$default</c> slot in
            /// the bytecode); user params are then matched positionally.</para>
            /// <para><b>InstanceField</b>: when set, the bridge calls an
            /// instance method on a Kotlin <c>object</c> singleton — name
            /// the <c>$$INSTANCE</c>-style static field
            /// (e.g. <c>INSTANCE</c>) and the generator emits
            /// <c>GetMethodID</c> + <c>CallObjectMethod</c> instead.</para>
            /// </remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method,
                                           AllowMultiple = false)]
            internal sealed class ComposeBridgeAttribute : global::System.Attribute
            {
                public ComposeBridgeAttribute() { }
                public string Class { get; set; } = "";
                public string JvmName { get; set; } = "";
                public string Signature { get; set; } = "";
                public global::System.Type? Defaults { get; set; }
                public string? InstanceField { get; set; }
            }
        }
        """;
}
