using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ComposeNet.SourceGenerators;

internal static class ComposeDefaultsEmitter
{
    public static string Emit(
        string enumName,
        INamedTypeSymbol containingType,
        IMethodSymbol method,
        int composerIndex)
    {
        var emitted = new List<(string Name, int Bit)>();
        for (int i = 0; i < composerIndex; i++)
        {
            var p = method.Parameters[i];
            if (ComposeDefaultsGenerator.IsKotlinFunction(p.Type))
                continue;
            emitted.Add((PascalCase(p.Name, i), i));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.Append("// Generated by ComposeNet.SourceGenerators from ");
        sb.Append(containingType.ToDisplayString());
        sb.Append('.');
        sb.AppendLine(method.Name);
        sb.AppendLine("// Bit positions match the Kotlin parameter index before the IComposer");
        sb.AppendLine("// parameter; Function-typed parameters (content lambdas) are skipped");
        sb.AppendLine("// because they are always provided and never defaulted.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace ComposeNet");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Flags]");
        sb.Append("    internal enum ").AppendLine(enumName);
        sb.AppendLine("    {");
        sb.AppendLine("        None = 0,");

        int maxNameLen = emitted.Count == 0 ? 0 : emitted.Max(e => e.Name.Length);
        foreach (var (name, bit) in emitted)
        {
            sb.Append("        ").Append(name).Append(' ', maxNameLen - name.Length)
              .Append(" = 1 << ").Append(bit).AppendLine(",");
        }

        // Note any skipped Function-typed parameters as a comment for traceability.
        for (int i = 0; i < composerIndex; i++)
        {
            var p = method.Parameters[i];
            if (!ComposeDefaultsGenerator.IsKotlinFunction(p.Type))
                continue;
            sb.Append("        // bit ").Append(i).Append(": ").Append(p.Name)
              .Append(" (").Append(p.Type.Name).AppendLine(") — always provided, no enum member.");
        }

        sb.AppendLine();
        sb.AppendLine("        /// <summary>OR of every user-defaultable bit.</summary>");
        if (emitted.Count == 0)
        {
            sb.AppendLine("        All = 0,");
        }
        else
        {
            sb.Append("        All = ");
            sb.Append(string.Join(" | ", emitted.Select(e => e.Name)));
            sb.AppendLine(",");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static string PascalCase(string raw, int positionFallback)
    {
        if (string.IsNullOrEmpty(raw))
            return "Param" + positionFallback;

        if (raw.Length >= 2 && raw[0] == 'p' && IsAllDigits(raw, 1))
            return "Param" + raw.Substring(1);

        if (char.IsUpper(raw[0]))
            return raw;

        return char.ToUpperInvariant(raw[0]) + raw.Substring(1);
    }

    static bool IsAllDigits(string s, int start)
    {
        for (int i = start; i < s.Length; i++)
            if (!char.IsDigit(s[i])) return false;
        return start < s.Length;
    }
}
