using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ComposeNet.SourceGenerators;

internal static class ComposeDefaultsEmitter
{
    /// <summary>
    /// One bit position in the generated enum.
    /// <see cref="EnumMember"/> is null when the bit is consumed (occupies
    /// a position) but no member is emitted — e.g. params the caller always
    /// provides, or Kotlin lambda content slots.
    /// </summary>
    public readonly struct Slot
    {
        public Slot(int bit, string? enumMember, string rawName, string? skipReason)
        {
            Bit = bit;
            EnumMember = enumMember;
            RawName = rawName;
            SkipReason = skipReason;
        }

        public int Bit { get; }
        public string? EnumMember { get; }
        public string RawName { get; }
        public string? SkipReason { get; }
    }

    /// <summary>Build slots from a Roslyn method symbol (generic attribute path).</summary>
    public static IReadOnlyList<Slot> SlotsFromSymbol(IMethodSymbol method, int composerIndex)
    {
        var slots = new List<Slot>(composerIndex);
        for (int i = 0; i < composerIndex; i++)
        {
            var p = method.Parameters[i];
            if (ComposeDefaultsGenerator.IsKotlinFunction(p.Type))
            {
                slots.Add(new Slot(i, null, p.Name, $"{p.Type.Name} — always provided, no enum member."));
                continue;
            }
            slots.Add(new Slot(i, PascalCase(p.Name, i), p.Name, null));
        }
        return slots;
    }

    /// <summary>Build slots from a positional name list (declarative attribute path).</summary>
    public static IReadOnlyList<Slot> SlotsFromNames(IReadOnlyList<string> names)
    {
        var slots = new List<Slot>(names.Count);
        for (int i = 0; i < names.Count; i++)
        {
            var raw = names[i] ?? string.Empty;
            if (raw.Length > 0 && raw[0] == '!')
            {
                var inner = raw.Substring(1);
                slots.Add(new Slot(i, null, inner, "marked '!' — always provided, no enum member."));
            }
            else
            {
                slots.Add(new Slot(i, PascalCase(raw, i), raw, null));
            }
        }
        return slots;
    }

    public static string Emit(string enumName, string sourceComment, IReadOnlyList<Slot> slots)
    {
        var members = slots.Where(s => s.EnumMember is not null).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.Append("// Generated by ComposeNet.SourceGenerators from ");
        sb.AppendLine(sourceComment);
        sb.AppendLine("// Bit positions match the Kotlin parameter index in the $default bitmask.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace ComposeNet");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Flags]");
        sb.Append("    internal enum ").AppendLine(enumName);
        sb.AppendLine("    {");
        sb.AppendLine("        None = 0,");

        int maxNameLen = members.Count == 0 ? 0 : members.Max(m => m.EnumMember!.Length);
        foreach (var slot in members)
        {
            sb.Append("        ").Append(slot.EnumMember).Append(' ', maxNameLen - slot.EnumMember!.Length)
              .Append(" = 1 << ").Append(slot.Bit).AppendLine(",");
        }

        foreach (var slot in slots)
        {
            if (slot.EnumMember is not null) continue;
            sb.Append("        // bit ").Append(slot.Bit).Append(": ").Append(slot.RawName)
              .Append(" — ").AppendLine(slot.SkipReason ?? "skipped.");
        }

        sb.AppendLine();
        sb.AppendLine("        /// <summary>OR of every user-defaultable bit.</summary>");
        if (members.Count == 0)
        {
            sb.AppendLine("        All = 0,");
        }
        else
        {
            sb.Append("        All = ");
            sb.Append(string.Join(" | ", members.Select(m => m.EnumMember)));
            sb.AppendLine(",");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static string PascalCase(string raw, int positionFallback)
    {
        if (string.IsNullOrEmpty(raw))
            return "Param" + positionFallback;

        if (raw.Length >= 2 && raw[0] == 'p' && IsAllDigits(raw, 1))
            return "Param" + raw.Substring(1);

        if (char.IsUpper(raw[0]))
            return raw;

        return char.ToUpperInvariant(raw[0]) + raw.Substring(1);
    }

    static bool IsAllDigits(string s, int start)
    {
        for (int i = start; i < s.Length; i++)
            if (!char.IsDigit(s[i])) return false;
        return start < s.Length;
    }
}

