namespace ComposeNet;

/// <summary>
/// Material 3 <c>Text</c> composable — renders a non-interactive
/// string with the current <see cref="MaterialTheme"/>'s typography.
/// </summary>
/// <remarks>
/// This facade body is generated by
/// <c>ComposeFacadeGenerator</c>; see the matching
/// <c>[ComposeFacade]</c>-decorated bridge in
/// <c>ComposeBridges.cs</c>.
/// </remarks>
public sealed partial class Text;
